---
abstract: 'Beautify Javascript (beautifier for javascript)'
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires:
  IO::File: '0'
  Pod::Usage: '0'
  Test::More: '0.88'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4224, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: JavaScript-Beautifier
provides:
  Code::TidyAll::Plugin::JSBeautifier:
    file: lib/Code/TidyAll/Plugin/JSBeautifier.pm
    version: '0.21'
  JavaScript::Beautifier:
    file: lib/JavaScript/Beautifier.pm
    version: '0.25'
requires:
  Getopt::Long: '0'
  IO::File: '0'
  Pod::Usage: '0'
  perl: v5.10.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/fayland/perl-javascript-beautifier/tree/master
version: '0.25'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
