---
name: JavaScript-Beautifier
version: 0.11
author:
  - 'Fayland Lam <fayland@gmail.com>'
abstract: Beautify Javascript (beautifier for javascript)
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/fayland/perl-javascript-beautifier/tree/master
build_requires:
  Getopt::Long: 0
  Pod::Usage: 0
  Test::More: 0
provides:
  JavaScript::Beautifier:
    file: lib/JavaScript/Beautifier.pm
    version: 0.11
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
